name: Build backend image

on:
  push:
    branches:
      - "main"

jobs:
  build_package:
    runs-on: ubuntu-latest
    name: Build package
    steps:
      - name: Install python packages
        run: |
          pip install poetry

      - name: Build package
        run: |
          ls ./
          poetry build
