name: Build backend image

on:
  push:
    branches:
      - "main"

jobs:
  build_package:
    runs-on: ubuntu-latest
    name: Build package
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install python packages
        run: |
          pip install poetry

      - name: Build package
        run: |
          poetry build
          poetry publish -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }}
